In [80]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression

df = pd.read_csv('../StackingData.csv')
X = np.array(df[['RTN_prob','CNN_prob']])
y = np.array(df[['label']])
clf = LogisticRegression(random_state=0).fit(X, y)
clf.predict(X)

In [115]:
df = pd.read_csv('./data/StackingData.csv')

In [92]:
df.head()

RTN_prob  CNN_prob  label
0      0.98  1.000000      0
1      0.90  1.000000      0
2      0.98  0.999963      0
3      1.00  0.999996      0
4      0.86  0.999691      0

In [101]:
X = np.array(df[['RTN_prob','CNN_prob']])
y = np.array(df[['label']])
X, y

(array([[9.8000000e-01, 1.0000000e+00],
        [9.0000000e-01, 1.0000000e+00],
        [9.8000000e-01, 9.9996257e-01],
        ...,
        [7.0000000e-02, 3.2716950e-08],
        [4.0000000e-01, 1.4339884e-05],
        [1.3000000e-01, 5.6273700e-04]]),
 array([[0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
    

In [64]:
a = np.array([[0.02, 0.98],[0.87,0.13]])
b = np.array([[0.99, 0.01],[0.12, 0.88]])
y = np.array([1, 0])
X = resize(a,b)

In [ ]:
clf.

In [102]:
clf = LogisticRegression(random_state=0).fit(X, y)

/opt/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [108]:
print(clf.predict(X) == y)

[[ True  True  True ... False False False]
 [ True  True  True ... False False False]
 [ True  True  True ... False False False]
 ...
 [False False False ...  True  True  True]
 [False False False ...  True  True  True]
 [False False False ...  True  True  True]]


In [75]:
def resize(a, b): # a: chan b: YJ
    if len(a.shape) == 2:
        a = np.swapaxes([a[:,0]],1,0)
        b = np.swapaxes([b[:,1]],1,0)
        return np.concatenate((a,b), axis=1)
    elif len(a.shape) == 1:
        return np.array((a[0], b[1]))
    else:
        return "wrong input shape"

In [81]:
output1 = np.array([0.02, 0.98])
output2 = np.array([0.99999, 0.00001])

In [110]:
inst = np.array([(output1[0],output2[1])])
inst

array([[2.e-02, 1.e-05]])

In [111]:
clf.predict(np.array(inst))

array([1])

In [113]:
clf.get_params

<bound method BaseEstimator.get_params of LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=0, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)>

In [76]:
resize(o1, o2)
X1 = resize(o1, o2)

array([2.e-02, 1.e-05])

In [78]:
clf.predict(X)

array([1, 0])